package iot;


import java.io.Serializable;

/**
 * A single temperature measurement as it flows from the REST API into the ETL.
 *
 * - uuid:        generated by the API per accepted request (infra-redelivery dedup key)
 * - ts:          device-reported timestamp (NOT trusted for ordering; used only for
 *                device-level duplicate-send dedup)
 * - apiIngestTs: assigned by the API at the earliest possible point on receipt
 *                (the trustworthy clock; drives event-time windowing in the ETL)
 *
 * Shaped as a Flink POJO (public no-arg constructor + non-final fields) so Flink
 * uses its efficient POJO serializer instead of falling back to Kryo.
 */
public class Measurement implements Serializable {
    public String uuid;
    public String customerId;
    public String deviceId;
    public long ts;
    public long apiIngestTs;
    public double reading;

    /** Required by Flink's POJO serializer. */
    public Measurement() {
    }

    public Measurement(String uuid, String customerId, String deviceId,
                        long ts, long apiIngestTs, double reading) {
        this.uuid = uuid;
        this.customerId = customerId;
        this.deviceId = deviceId;
        this.ts = ts;
        this.apiIngestTs = apiIngestTs;
        this.reading = reading;
    }

    /** Partition/state key: DeviceID@CustomerID (device IDs are not globally unique). */
    public String deviceKey() {
        return deviceId + "@" + customerId;
    }

    @Override
    public String toString() {
        return String.format("Measurement{uuid=%s, key=%s, ts=%d, apiIngestTs=%d, reading=%.1f}",
                uuid, deviceKey(), ts, apiIngestTs, reading);
    }
}